#!/bin/bash
cp implementation/system.bit ../bit_files/chan_packet_2012_Jul_16_1347.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/chan_packet_2012_Jul_16_1347.bof
