import unittest
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from autofit import autofit

import matplotlib.pyplot as plt
class TestAutofit(unittest.TestCase):

    def testAutofit(self):
        # This is the wide sweep file, generated by the labview program
        # SegmentedSweep
        wsfn = '20131016adr/FL2.txt'

        # This is the approximate resonance location file, generated by
        # WideAna.pro or WideAna.py
        rlfn = '20131016adr/FL2-right.txt'
        af = autofit(wsfn,rlfn)
        af.run(1,plotFileName="testAutofit.pdf")

if __name__ == '__main__':
    unittest.main()

