# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arcons_basic_gui.ui'
#
# Created: Sat Jul 30 21:38:09 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_arcons(object):
    def setupUi(self, arcons):
        arcons.setObjectName(_fromUtf8("arcons"))
        arcons.setEnabled(True)
        arcons.resize(731, 801)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(arcons.sizePolicy().hasHeightForWidth())
        arcons.setSizePolicy(sizePolicy)
        arcons.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Archon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        arcons.setWindowIcon(icon)
        arcons.setWindowFilePath(_fromUtf8(""))
        arcons.setAnimated(True)
        self.centralwidget = QtGui.QWidget(arcons)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 151))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.array_temp_lcd = QtGui.QLCDNumber(self.frame)
        self.array_temp_lcd.setGeometry(QtCore.QRect(10, 40, 81, 41))
        self.array_temp_lcd.setObjectName(_fromUtf8("array_temp_lcd"))
        self.pulse_tube_temp_lcd = QtGui.QLCDNumber(self.frame)
        self.pulse_tube_temp_lcd.setGeometry(QtCore.QRect(10, 90, 81, 41))
        self.pulse_tube_temp_lcd.setObjectName(_fromUtf8("pulse_tube_temp_lcd"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.open_shutter_radioButton = QtGui.QRadioButton(self.frame)
        self.open_shutter_radioButton.setEnabled(False)
        self.open_shutter_radioButton.setGeometry(QtCore.QRect(240, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.open_shutter_radioButton.setFont(font)
        self.open_shutter_radioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_shutter_radioButton.setAutoExclusive(False)
        self.open_shutter_radioButton.setObjectName(_fromUtf8("open_shutter_radioButton"))
        self.cycle_fridge_radioButton = QtGui.QRadioButton(self.frame)
        self.cycle_fridge_radioButton.setEnabled(False)
        self.cycle_fridge_radioButton.setGeometry(QtCore.QRect(240, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cycle_fridge_radioButton.setFont(font)
        self.cycle_fridge_radioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cycle_fridge_radioButton.setAutoExclusive(False)
        self.cycle_fridge_radioButton.setObjectName(_fromUtf8("cycle_fridge_radioButton"))
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 180, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(390, 0, 341, 181))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.compass_graphicsView = QtGui.QGraphicsView(self.frame_2)
        self.compass_graphicsView.setGeometry(QtCore.QRect(50, 90, 81, 81))
        self.compass_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compass_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compass_graphicsView.setInteractive(False)
        self.compass_graphicsView.setObjectName(_fromUtf8("compass_graphicsView"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(170, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(160, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(150, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(150, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(150, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(170, 100, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.status_label = QtGui.QLabel(self.frame_2)
        self.status_label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setFrameShape(QtGui.QFrame.Box)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.local_time_label = QtGui.QLabel(self.frame_2)
        self.local_time_label.setGeometry(QtCore.QRect(210, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.local_time_label.setFont(font)
        self.local_time_label.setFrameShape(QtGui.QFrame.Box)
        self.local_time_label.setText(_fromUtf8(""))
        self.local_time_label.setObjectName(_fromUtf8("local_time_label"))
        self.utc_label = QtGui.QLabel(self.frame_2)
        self.utc_label.setGeometry(QtCore.QRect(210, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.utc_label.setFont(font)
        self.utc_label.setFrameShape(QtGui.QFrame.Box)
        self.utc_label.setText(_fromUtf8(""))
        self.utc_label.setObjectName(_fromUtf8("utc_label"))
        self.lst_label = QtGui.QLabel(self.frame_2)
        self.lst_label.setGeometry(QtCore.QRect(210, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lst_label.setFont(font)
        self.lst_label.setFrameShape(QtGui.QFrame.Box)
        self.lst_label.setText(_fromUtf8(""))
        self.lst_label.setObjectName(_fromUtf8("lst_label"))
        self.airmass_label = QtGui.QLabel(self.frame_2)
        self.airmass_label.setGeometry(QtCore.QRect(210, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.airmass_label.setFont(font)
        self.airmass_label.setFrameShape(QtGui.QFrame.Box)
        self.airmass_label.setText(_fromUtf8(""))
        self.airmass_label.setObjectName(_fromUtf8("airmass_label"))
        self.az_label = QtGui.QLabel(self.frame_2)
        self.az_label.setGeometry(QtCore.QRect(210, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.az_label.setFont(font)
        self.az_label.setFrameShape(QtGui.QFrame.Box)
        self.az_label.setText(_fromUtf8(""))
        self.az_label.setObjectName(_fromUtf8("az_label"))
        self.alt_label = QtGui.QLabel(self.frame_2)
        self.alt_label.setGeometry(QtCore.QRect(210, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alt_label.setFont(font)
        self.alt_label.setFrameShape(QtGui.QFrame.Box)
        self.alt_label.setText(_fromUtf8(""))
        self.alt_label.setObjectName(_fromUtf8("alt_label"))
        self.ra_label = QtGui.QLabel(self.frame_2)
        self.ra_label.setGeometry(QtCore.QRect(40, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ra_label.setFont(font)
        self.ra_label.setFrameShape(QtGui.QFrame.Box)
        self.ra_label.setText(_fromUtf8(""))
        self.ra_label.setObjectName(_fromUtf8("ra_label"))
        self.dec_label = QtGui.QLabel(self.frame_2)
        self.dec_label.setGeometry(QtCore.QRect(40, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dec_label.setFont(font)
        self.dec_label.setFrameShape(QtGui.QFrame.Box)
        self.dec_label.setText(_fromUtf8(""))
        self.dec_label.setObjectName(_fromUtf8("dec_label"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 150, 391, 361))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.save_raw_checkBox = QtGui.QCheckBox(self.frame_3)
        self.save_raw_checkBox.setEnabled(False)
        self.save_raw_checkBox.setGeometry(QtCore.QRect(300, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_raw_checkBox.setFont(font)
        self.save_raw_checkBox.setObjectName(_fromUtf8("save_raw_checkBox"))
        self.data_directory_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.data_directory_lineEdit.setGeometry(QtCore.QRect(110, 40, 201, 21))
        self.data_directory_lineEdit.setObjectName(_fromUtf8("data_directory_lineEdit"))
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(20, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(150, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(20, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.calibrate_data_checkBox = QtGui.QCheckBox(self.frame_3)
        self.calibrate_data_checkBox.setEnabled(False)
        self.calibrate_data_checkBox.setGeometry(QtCore.QRect(280, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calibrate_data_checkBox.setFont(font)
        self.calibrate_data_checkBox.setObjectName(_fromUtf8("calibrate_data_checkBox"))
        self.stop_observation_pushButton = QtGui.QPushButton(self.frame_3)
        self.stop_observation_pushButton.setGeometry(QtCore.QRect(190, 190, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_observation_pushButton.setFont(font)
        self.stop_observation_pushButton.setObjectName(_fromUtf8("stop_observation_pushButton"))
        self.start_observation_pushButton = QtGui.QPushButton(self.frame_3)
        self.start_observation_pushButton.setGeometry(QtCore.QRect(190, 140, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_observation_pushButton.setFont(font)
        self.start_observation_pushButton.setObjectName(_fromUtf8("start_observation_pushButton"))
        self.close_pushButton = QtGui.QPushButton(self.frame_3)
        self.close_pushButton.setGeometry(QtCore.QRect(50, 310, 121, 41))
        self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        self.search_pushButton = QtGui.QPushButton(self.frame_3)
        self.search_pushButton.setGeometry(QtCore.QRect(320, 40, 61, 21))
        self.search_pushButton.setObjectName(_fromUtf8("search_pushButton"))
        self.obs_time_spinBox = QtGui.QSpinBox(self.frame_3)
        self.obs_time_spinBox.setGeometry(QtCore.QRect(110, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.obs_time_spinBox.setFont(font)
        self.obs_time_spinBox.setMaximum(99999)
        self.obs_time_spinBox.setProperty(_fromUtf8("value"), 30)
        self.obs_time_spinBox.setObjectName(_fromUtf8("obs_time_spinBox"))
        self.remaining_time_lcdNumber = QtGui.QLCDNumber(self.frame_3)
        self.remaining_time_lcdNumber.setGeometry(QtCore.QRect(110, 190, 61, 31))
        self.remaining_time_lcdNumber.setObjectName(_fromUtf8("remaining_time_lcdNumber"))
        self.frequency_tuneup_pushButton = QtGui.QPushButton(self.frame_3)
        self.frequency_tuneup_pushButton.setEnabled(False)
        self.frequency_tuneup_pushButton.setGeometry(QtCore.QRect(50, 250, 121, 51))
        self.frequency_tuneup_pushButton.setObjectName(_fromUtf8("frequency_tuneup_pushButton"))
        self.file_name_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.file_name_lineEdit.setEnabled(False)
        self.file_name_lineEdit.setGeometry(QtCore.QRect(82, 70, 211, 22))
        self.file_name_lineEdit.setText(_fromUtf8(""))
        self.file_name_lineEdit.setObjectName(_fromUtf8("file_name_lineEdit"))
        self.target_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.target_lineEdit.setGeometry(QtCore.QRect(100, 100, 171, 22))
        self.target_lineEdit.setObjectName(_fromUtf8("target_lineEdit"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(210, 240, 141, 111))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.subtract_sky_radioButton = QtGui.QRadioButton(self.frame_6)
        self.subtract_sky_radioButton.setGeometry(QtCore.QRect(20, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subtract_sky_radioButton.setFont(font)
        self.subtract_sky_radioButton.setChecked(False)
        self.subtract_sky_radioButton.setAutoExclusive(False)
        self.subtract_sky_radioButton.setObjectName(_fromUtf8("subtract_sky_radioButton"))
        self.image_color_radioButton = QtGui.QRadioButton(self.frame_6)
        self.image_color_radioButton.setEnabled(False)
        self.image_color_radioButton.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image_color_radioButton.setFont(font)
        self.image_color_radioButton.setChecked(False)
        self.image_color_radioButton.setAutoExclusive(False)
        self.image_color_radioButton.setObjectName(_fromUtf8("image_color_radioButton"))
        self.int_time_spinBox = QtGui.QSpinBox(self.frame_6)
        self.int_time_spinBox.setGeometry(QtCore.QRect(10, 50, 51, 22))
        self.int_time_spinBox.setMaximum(9999)
        self.int_time_spinBox.setProperty(_fromUtf8("value"), 1)
        self.int_time_spinBox.setObjectName(_fromUtf8("int_time_spinBox"))
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(60, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.options_radioButton = QtGui.QRadioButton(self.frame_6)
        self.options_radioButton.setGeometry(QtCore.QRect(10, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.options_radioButton.setFont(font)
        self.options_radioButton.setObjectName(_fromUtf8("options_radioButton"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(390, 180, 341, 331))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.tv_image = QtGui.QGraphicsView(self.frame_4)
        self.tv_image.setGeometry(QtCore.QRect(10, 0, 321, 321))
        self.tv_image.setMouseTracking(True)
        self.tv_image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tv_image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tv_image.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tv_image.setObjectName(_fromUtf8("tv_image"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 510, 731, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.spectra_plot = MPL_Widget(self.frame_5)
        self.spectra_plot.setGeometry(QtCore.QRect(230, 0, 491, 241))
        self.spectra_plot.setObjectName(_fromUtf8("spectra_plot"))
        self.pixel_number_label = QtGui.QLabel(self.frame_5)
        self.pixel_number_label.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.pixel_number_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.pixel_number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pixel_number_label.setObjectName(_fromUtf8("pixel_number_label"))
        self.pixel_no_lcd = QtGui.QLCDNumber(self.frame_5)
        self.pixel_no_lcd.setGeometry(QtCore.QRect(50, 100, 81, 31))
        self.pixel_no_lcd.setObjectName(_fromUtf8("pixel_no_lcd"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(740, 10, 181, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.drag_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.drag_select_radioButton.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.drag_select_radioButton.setAutoExclusive(False)
        self.drag_select_radioButton.setObjectName(_fromUtf8("drag_select_radioButton"))
        self.mode_buttonGroup = QtGui.QButtonGroup(arcons)
        self.mode_buttonGroup.setObjectName(_fromUtf8("mode_buttonGroup"))
        self.mode_buttonGroup.addButton(self.drag_select_radioButton)
        self.rect_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.rect_select_radioButton.setGeometry(QtCore.QRect(10, 70, 161, 21))
        self.rect_select_radioButton.setChecked(True)
        self.rect_select_radioButton.setAutoExclusive(False)
        self.rect_select_radioButton.setObjectName(_fromUtf8("rect_select_radioButton"))
        self.mode_buttonGroup.addButton(self.rect_select_radioButton)
        self.rect_x_spinBox = QtGui.QSpinBox(self.groupBox)
        self.rect_x_spinBox.setGeometry(QtCore.QRect(40, 90, 57, 31))
        self.rect_x_spinBox.setMinimum(1)
        self.rect_x_spinBox.setMaximum(32)
        self.rect_x_spinBox.setProperty(_fromUtf8("value"), 1)
        self.rect_x_spinBox.setObjectName(_fromUtf8("rect_x_spinBox"))
        self.rect_y_spinBox = QtGui.QSpinBox(self.groupBox)
        self.rect_y_spinBox.setGeometry(QtCore.QRect(120, 90, 57, 31))
        self.rect_y_spinBox.setMinimum(1)
        self.rect_y_spinBox.setMaximum(32)
        self.rect_y_spinBox.setProperty(_fromUtf8("value"), 1)
        self.rect_y_spinBox.setObjectName(_fromUtf8("rect_y_spinBox"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(30, 90, 16, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(110, 90, 16, 31))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.circ_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.circ_select_radioButton.setGeometry(QtCore.QRect(10, 130, 151, 21))
        self.circ_select_radioButton.setAutoExclusive(False)
        self.circ_select_radioButton.setObjectName(_fromUtf8("circ_select_radioButton"))
        self.mode_buttonGroup.addButton(self.circ_select_radioButton)
        self.circ_r_spinBox = QtGui.QSpinBox(self.groupBox)
        self.circ_r_spinBox.setGeometry(QtCore.QRect(40, 150, 57, 31))
        self.circ_r_spinBox.setMinimum(0)
        self.circ_r_spinBox.setMaximum(16)
        self.circ_r_spinBox.setProperty(_fromUtf8("value"), 0)
        self.circ_r_spinBox.setObjectName(_fromUtf8("circ_r_spinBox"))
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(30, 150, 16, 31))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(740, 680, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(740, 640, 46, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.RA_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.RA_lineEdit.setEnabled(False)
        self.RA_lineEdit.setGeometry(QtCore.QRect(740, 650, 113, 20))
        self.RA_lineEdit.setObjectName(_fromUtf8("RA_lineEdit"))
        self.Dec_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.Dec_lineEdit.setEnabled(False)
        self.Dec_lineEdit.setGeometry(QtCore.QRect(740, 690, 113, 20))
        self.Dec_lineEdit.setObjectName(_fromUtf8("Dec_lineEdit"))
        self.simple_imaging_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.simple_imaging_radioButton.setEnabled(False)
        self.simple_imaging_radioButton.setGeometry(QtCore.QRect(740, 720, 211, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simple_imaging_radioButton.sizePolicy().hasHeightForWidth())
        self.simple_imaging_radioButton.setSizePolicy(sizePolicy)
        self.simple_imaging_radioButton.setCheckable(True)
        self.simple_imaging_radioButton.setChecked(False)
        self.simple_imaging_radioButton.setAutoExclusive(False)
        self.simple_imaging_radioButton.setObjectName(_fromUtf8("simple_imaging_radioButton"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(740, 610, 101, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.choose_beamimage = QtGui.QPushButton(self.centralwidget)
        self.choose_beamimage.setGeometry(QtCore.QRect(740, 210, 171, 41))
        self.choose_beamimage.setObjectName(_fromUtf8("choose_beamimage"))
        self.choose_bindir = QtGui.QPushButton(self.centralwidget)
        self.choose_bindir.setGeometry(QtCore.QRect(740, 250, 171, 41))
        self.choose_bindir.setObjectName(_fromUtf8("choose_bindir"))
        self.brightpix = QtGui.QSpinBox(self.centralwidget)
        self.brightpix.setGeometry(QtCore.QRect(750, 300, 57, 25))
        self.brightpix.setMaximum(1024)
        self.brightpix.setProperty(_fromUtf8("value"), 40)
        self.brightpix.setObjectName(_fromUtf8("brightpix"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(811, 300, 91, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.takesky = QtGui.QPushButton(self.centralwidget)
        self.takesky.setGeometry(QtCore.QRect(740, 380, 171, 51))
        self.takesky.setObjectName(_fromUtf8("takesky"))
        arcons.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(arcons)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        arcons.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(arcons)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        arcons.setStatusBar(self.statusbar)

        self.retranslateUi(arcons)
        QtCore.QObject.connect(self.close_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), arcons.close)
        QtCore.QMetaObject.connectSlotsByName(arcons)

    def retranslateUi(self, arcons):
        arcons.setWindowTitle(QtGui.QApplication.translate("arcons", "ARCONS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("arcons", "ARCONS Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("arcons", "Array Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("arcons", "Pulse Tube Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.open_shutter_radioButton.setText(QtGui.QApplication.translate("arcons", "Open Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.cycle_fridge_radioButton.setText(QtGui.QApplication.translate("arcons", "Cycle Fridge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("arcons", "Telescope Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("arcons", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("arcons", "Dec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("arcons", "UTC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("arcons", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("arcons", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("arcons", "Local Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("arcons", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("arcons", "LST", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("arcons", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.save_raw_checkBox.setText(QtGui.QApplication.translate("arcons", " Save Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("arcons", "Data Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("arcons", "Remaining time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("arcons", "SDR Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("arcons", "Exposure Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrate_data_checkBox.setText(QtGui.QApplication.translate("arcons", "Calibrate Data", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_observation_pushButton.setText(QtGui.QApplication.translate("arcons", "Stop Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.start_observation_pushButton.setText(QtGui.QApplication.translate("arcons", "Start Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("arcons", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.search_pushButton.setText(QtGui.QApplication.translate("arcons", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency_tuneup_pushButton.setText(QtGui.QApplication.translate("arcons", "Frequency \n"
"Tune-up", None, QtGui.QApplication.UnicodeUTF8))
        self.target_lineEdit.setText(QtGui.QApplication.translate("arcons", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("arcons", "File name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("arcons", "Target name:", None, QtGui.QApplication.UnicodeUTF8))
        self.subtract_sky_radioButton.setText(QtGui.QApplication.translate("arcons", "Subtract Sky", None, QtGui.QApplication.UnicodeUTF8))
        self.image_color_radioButton.setText(QtGui.QApplication.translate("arcons", "Image Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("arcons", " Integration (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.options_radioButton.setText(QtGui.QApplication.translate("arcons", "Plot Options -->", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_number_label.setText(QtGui.QApplication.translate("arcons", "Displaying Plot for\n"
" Pixel Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("arcons", "Pixel Selection Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.drag_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Click && Drag", None, QtGui.QApplication.UnicodeUTF8))
        self.rect_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Single Click Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("arcons", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("arcons", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.circ_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Single Click Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("arcons", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("arcons", "Dec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("arcons", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.RA_lineEdit.setText(QtGui.QApplication.translate("arcons", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Dec_lineEdit.setText(QtGui.QApplication.translate("arcons", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.simple_imaging_radioButton.setText(QtGui.QApplication.translate("arcons", "Simple Images (counts only)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("arcons", "Testing Junk", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_beamimage.setText(QtGui.QApplication.translate("arcons", "Choose Beamimage", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_bindir.setText(QtGui.QApplication.translate("arcons", "Choose Bin Dir.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("arcons", "Brightest Pix", None, QtGui.QApplication.UnicodeUTF8))
        self.takesky.setText(QtGui.QApplication.translate("arcons", "Take Sky Exposure", None, QtGui.QApplication.UnicodeUTF8))

from mpl_pyqt4_widget import MPL_Widget
