#!/bin/bash
cp implementation/system.bit ../bit_files/chan_512_packet_2012_Jul_19_1704.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/chan_512_packet_2012_Jul_19_1704.bof
