# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arcons_basic_gui.ui'
#
# Created: Fri Sep 14 05:34:13 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_arcons(object):
    def setupUi(self, arcons):
        arcons.setObjectName(_fromUtf8("arcons"))
        arcons.setEnabled(True)
        arcons.resize(860, 960)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(arcons.sizePolicy().hasHeightForWidth())
        arcons.setSizePolicy(sizePolicy)
        arcons.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("lib/Archon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        arcons.setWindowIcon(icon)
        arcons.setWindowFilePath(_fromUtf8(""))
        arcons.setAnimated(True)
        self.centralwidget = QtGui.QWidget(arcons)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 151))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.array_temp_lcd = QtGui.QLCDNumber(self.frame)
        self.array_temp_lcd.setGeometry(QtCore.QRect(10, 40, 81, 41))
        self.array_temp_lcd.setObjectName(_fromUtf8("array_temp_lcd"))
        self.pulse_tube_temp_lcd = QtGui.QLCDNumber(self.frame)
        self.pulse_tube_temp_lcd.setGeometry(QtCore.QRect(10, 90, 81, 41))
        self.pulse_tube_temp_lcd.setObjectName(_fromUtf8("pulse_tube_temp_lcd"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.open_shutter_radioButton = QtGui.QRadioButton(self.frame)
        self.open_shutter_radioButton.setEnabled(False)
        self.open_shutter_radioButton.setGeometry(QtCore.QRect(240, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.open_shutter_radioButton.setFont(font)
        self.open_shutter_radioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_shutter_radioButton.setAutoExclusive(False)
        self.open_shutter_radioButton.setObjectName(_fromUtf8("open_shutter_radioButton"))
        self.cycle_fridge_radioButton = QtGui.QRadioButton(self.frame)
        self.cycle_fridge_radioButton.setEnabled(False)
        self.cycle_fridge_radioButton.setGeometry(QtCore.QRect(240, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cycle_fridge_radioButton.setFont(font)
        self.cycle_fridge_radioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cycle_fridge_radioButton.setAutoExclusive(False)
        self.cycle_fridge_radioButton.setObjectName(_fromUtf8("cycle_fridge_radioButton"))
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 180, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(390, 0, 471, 181))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(150, 0, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.compass_graphicsView = QtGui.QGraphicsView(self.frame_2)
        self.compass_graphicsView.setGeometry(QtCore.QRect(70, 90, 81, 81))
        self.compass_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compass_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compass_graphicsView.setInteractive(False)
        self.compass_graphicsView.setObjectName(_fromUtf8("compass_graphicsView"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(170, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(180, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(180, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(150, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(150, 80, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(170, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.status_label = QtGui.QLabel(self.frame_2)
        self.status_label.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setFrameShape(QtGui.QFrame.Box)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.local_time_label = QtGui.QLabel(self.frame_2)
        self.local_time_label.setGeometry(QtCore.QRect(290, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.local_time_label.setFont(font)
        self.local_time_label.setFrameShape(QtGui.QFrame.Box)
        self.local_time_label.setText(_fromUtf8(""))
        self.local_time_label.setObjectName(_fromUtf8("local_time_label"))
        self.utc_label = QtGui.QLabel(self.frame_2)
        self.utc_label.setGeometry(QtCore.QRect(290, 120, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.utc_label.setFont(font)
        self.utc_label.setFrameShape(QtGui.QFrame.Box)
        self.utc_label.setText(_fromUtf8(""))
        self.utc_label.setObjectName(_fromUtf8("utc_label"))
        self.lst_label = QtGui.QLabel(self.frame_2)
        self.lst_label.setGeometry(QtCore.QRect(290, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lst_label.setFont(font)
        self.lst_label.setFrameShape(QtGui.QFrame.Box)
        self.lst_label.setText(_fromUtf8(""))
        self.lst_label.setObjectName(_fromUtf8("lst_label"))
        self.airmass_label = QtGui.QLabel(self.frame_2)
        self.airmass_label.setGeometry(QtCore.QRect(290, 80, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.airmass_label.setFont(font)
        self.airmass_label.setFrameShape(QtGui.QFrame.Box)
        self.airmass_label.setText(_fromUtf8(""))
        self.airmass_label.setObjectName(_fromUtf8("airmass_label"))
        self.az_label = QtGui.QLabel(self.frame_2)
        self.az_label.setGeometry(QtCore.QRect(290, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.az_label.setFont(font)
        self.az_label.setFrameShape(QtGui.QFrame.Box)
        self.az_label.setText(_fromUtf8(""))
        self.az_label.setObjectName(_fromUtf8("az_label"))
        self.alt_label = QtGui.QLabel(self.frame_2)
        self.alt_label.setGeometry(QtCore.QRect(290, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alt_label.setFont(font)
        self.alt_label.setFrameShape(QtGui.QFrame.Box)
        self.alt_label.setText(_fromUtf8(""))
        self.alt_label.setObjectName(_fromUtf8("alt_label"))
        self.ra_label = QtGui.QLabel(self.frame_2)
        self.ra_label.setGeometry(QtCore.QRect(50, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ra_label.setFont(font)
        self.ra_label.setFrameShape(QtGui.QFrame.Box)
        self.ra_label.setText(_fromUtf8(""))
        self.ra_label.setObjectName(_fromUtf8("ra_label"))
        self.dec_label = QtGui.QLabel(self.frame_2)
        self.dec_label.setGeometry(QtCore.QRect(50, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dec_label.setFont(font)
        self.dec_label.setFrameShape(QtGui.QFrame.Box)
        self.dec_label.setText(_fromUtf8(""))
        self.dec_label.setObjectName(_fromUtf8("dec_label"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 150, 391, 521))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.save_raw_checkBox = QtGui.QCheckBox(self.frame_3)
        self.save_raw_checkBox.setEnabled(False)
        self.save_raw_checkBox.setGeometry(QtCore.QRect(300, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_raw_checkBox.setFont(font)
        self.save_raw_checkBox.setObjectName(_fromUtf8("save_raw_checkBox"))
        self.data_directory_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.data_directory_lineEdit.setGeometry(QtCore.QRect(110, 40, 201, 21))
        self.data_directory_lineEdit.setObjectName(_fromUtf8("data_directory_lineEdit"))
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(20, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(120, 0, 241, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(20, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.calibrate_data_checkBox = QtGui.QCheckBox(self.frame_3)
        self.calibrate_data_checkBox.setEnabled(False)
        self.calibrate_data_checkBox.setGeometry(QtCore.QRect(280, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calibrate_data_checkBox.setFont(font)
        self.calibrate_data_checkBox.setObjectName(_fromUtf8("calibrate_data_checkBox"))
        self.stop_observation_pushButton = QtGui.QPushButton(self.frame_3)
        self.stop_observation_pushButton.setGeometry(QtCore.QRect(200, 200, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_observation_pushButton.setFont(font)
        self.stop_observation_pushButton.setObjectName(_fromUtf8("stop_observation_pushButton"))
        self.start_observation_pushButton = QtGui.QPushButton(self.frame_3)
        self.start_observation_pushButton.setGeometry(QtCore.QRect(200, 140, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_observation_pushButton.setFont(font)
        self.start_observation_pushButton.setObjectName(_fromUtf8("start_observation_pushButton"))
        self.close_pushButton = QtGui.QPushButton(self.frame_3)
        self.close_pushButton.setGeometry(QtCore.QRect(50, 460, 121, 41))
        self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        self.search_pushButton = QtGui.QPushButton(self.frame_3)
        self.search_pushButton.setGeometry(QtCore.QRect(320, 40, 61, 21))
        self.search_pushButton.setObjectName(_fromUtf8("search_pushButton"))
        self.obs_time_spinBox = QtGui.QSpinBox(self.frame_3)
        self.obs_time_spinBox.setGeometry(QtCore.QRect(120, 170, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.obs_time_spinBox.setFont(font)
        self.obs_time_spinBox.setMaximum(99999)
        self.obs_time_spinBox.setProperty(_fromUtf8("value"), 30)
        self.obs_time_spinBox.setObjectName(_fromUtf8("obs_time_spinBox"))
        self.remaining_time_lcdNumber = QtGui.QLCDNumber(self.frame_3)
        self.remaining_time_lcdNumber.setGeometry(QtCore.QRect(120, 210, 61, 21))
        self.remaining_time_lcdNumber.setObjectName(_fromUtf8("remaining_time_lcdNumber"))
        self.frequency_tuneup_pushButton = QtGui.QPushButton(self.frame_3)
        self.frequency_tuneup_pushButton.setEnabled(False)
        self.frequency_tuneup_pushButton.setGeometry(QtCore.QRect(50, 400, 121, 51))
        self.frequency_tuneup_pushButton.setObjectName(_fromUtf8("frequency_tuneup_pushButton"))
        self.file_name_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.file_name_lineEdit.setEnabled(False)
        self.file_name_lineEdit.setGeometry(QtCore.QRect(82, 70, 211, 22))
        self.file_name_lineEdit.setText(_fromUtf8(""))
        self.file_name_lineEdit.setObjectName(_fromUtf8("file_name_lineEdit"))
        self.target_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.target_lineEdit.setGeometry(QtCore.QRect(100, 100, 171, 22))
        self.target_lineEdit.setObjectName(_fromUtf8("target_lineEdit"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(210, 390, 141, 111))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.subtract_sky_radioButton = QtGui.QRadioButton(self.frame_6)
        self.subtract_sky_radioButton.setGeometry(QtCore.QRect(20, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subtract_sky_radioButton.setFont(font)
        self.subtract_sky_radioButton.setChecked(False)
        self.subtract_sky_radioButton.setAutoExclusive(False)
        self.subtract_sky_radioButton.setObjectName(_fromUtf8("subtract_sky_radioButton"))
        self.image_color_radioButton = QtGui.QRadioButton(self.frame_6)
        self.image_color_radioButton.setEnabled(False)
        self.image_color_radioButton.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image_color_radioButton.setFont(font)
        self.image_color_radioButton.setChecked(False)
        self.image_color_radioButton.setAutoExclusive(False)
        self.image_color_radioButton.setObjectName(_fromUtf8("image_color_radioButton"))
        self.int_time_spinBox = QtGui.QSpinBox(self.frame_6)
        self.int_time_spinBox.setGeometry(QtCore.QRect(10, 50, 51, 22))
        self.int_time_spinBox.setMaximum(9999)
        self.int_time_spinBox.setProperty(_fromUtf8("value"), 1)
        self.int_time_spinBox.setObjectName(_fromUtf8("int_time_spinBox"))
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(60, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.options_radioButton = QtGui.QRadioButton(self.frame_6)
        self.options_radioButton.setGeometry(QtCore.QRect(10, 80, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.options_radioButton.setFont(font)
        self.options_radioButton.setObjectName(_fromUtf8("options_radioButton"))
        self.textEdit = QtGui.QTextEdit(self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 260, 371, 101))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_27 = QtGui.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(10, 240, 151, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.update_description = QtGui.QPushButton(self.frame_3)
        self.update_description.setGeometry(QtCore.QRect(10, 360, 141, 31))
        self.update_description.setObjectName(_fromUtf8("update_description"))
        self.continuous = QtGui.QCheckBox(self.frame_3)
        self.continuous.setGeometry(QtCore.QRect(20, 130, 181, 41))
        self.continuous.setObjectName(_fromUtf8("continuous"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(390, 180, 471, 491))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.tv_image = QtGui.QGraphicsView(self.frame_4)
        self.tv_image.setGeometry(QtCore.QRect(10, 10, 444, 464))
        self.tv_image.setMouseTracking(True)
        self.tv_image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tv_image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tv_image.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tv_image.setObjectName(_fromUtf8("tv_image"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 670, 861, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.spectra_plot = MPL_Widget(self.frame_5)
        self.spectra_plot.setGeometry(QtCore.QRect(250, 0, 491, 241))
        self.spectra_plot.setObjectName(_fromUtf8("spectra_plot"))
        self.pixel_number_label = QtGui.QLabel(self.frame_5)
        self.pixel_number_label.setGeometry(QtCore.QRect(40, 50, 131, 31))
        self.pixel_number_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.pixel_number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pixel_number_label.setObjectName(_fromUtf8("pixel_number_label"))
        self.pixelpath = QtGui.QLabel(self.frame_5)
        self.pixelpath.setGeometry(QtCore.QRect(40, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pixelpath.setFont(font)
        self.pixelpath.setFrameShape(QtGui.QFrame.Box)
        self.pixelpath.setText(_fromUtf8(""))
        self.pixelpath.setObjectName(_fromUtf8("pixelpath"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(870, 10, 171, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.drag_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.drag_select_radioButton.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.drag_select_radioButton.setAutoExclusive(False)
        self.drag_select_radioButton.setObjectName(_fromUtf8("drag_select_radioButton"))
        self.mode_buttonGroup = QtGui.QButtonGroup(arcons)
        self.mode_buttonGroup.setObjectName(_fromUtf8("mode_buttonGroup"))
        self.mode_buttonGroup.addButton(self.drag_select_radioButton)
        self.rect_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.rect_select_radioButton.setGeometry(QtCore.QRect(10, 70, 161, 21))
        self.rect_select_radioButton.setChecked(True)
        self.rect_select_radioButton.setAutoExclusive(False)
        self.rect_select_radioButton.setObjectName(_fromUtf8("rect_select_radioButton"))
        self.mode_buttonGroup.addButton(self.rect_select_radioButton)
        self.rect_x_spinBox = QtGui.QSpinBox(self.groupBox)
        self.rect_x_spinBox.setGeometry(QtCore.QRect(30, 90, 57, 31))
        self.rect_x_spinBox.setMinimum(1)
        self.rect_x_spinBox.setMaximum(32)
        self.rect_x_spinBox.setProperty(_fromUtf8("value"), 1)
        self.rect_x_spinBox.setObjectName(_fromUtf8("rect_x_spinBox"))
        self.rect_y_spinBox = QtGui.QSpinBox(self.groupBox)
        self.rect_y_spinBox.setGeometry(QtCore.QRect(110, 90, 57, 31))
        self.rect_y_spinBox.setMinimum(1)
        self.rect_y_spinBox.setMaximum(32)
        self.rect_y_spinBox.setProperty(_fromUtf8("value"), 1)
        self.rect_y_spinBox.setObjectName(_fromUtf8("rect_y_spinBox"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(20, 90, 16, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(100, 90, 16, 31))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.circ_select_radioButton = QtGui.QRadioButton(self.groupBox)
        self.circ_select_radioButton.setGeometry(QtCore.QRect(10, 130, 151, 21))
        self.circ_select_radioButton.setAutoExclusive(False)
        self.circ_select_radioButton.setObjectName(_fromUtf8("circ_select_radioButton"))
        self.mode_buttonGroup.addButton(self.circ_select_radioButton)
        self.circ_r_spinBox = QtGui.QSpinBox(self.groupBox)
        self.circ_r_spinBox.setGeometry(QtCore.QRect(40, 150, 57, 31))
        self.circ_r_spinBox.setMinimum(0)
        self.circ_r_spinBox.setMaximum(16)
        self.circ_r_spinBox.setProperty(_fromUtf8("value"), 0)
        self.circ_r_spinBox.setObjectName(_fromUtf8("circ_r_spinBox"))
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(30, 150, 16, 31))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.choose_beamimage = QtGui.QPushButton(self.centralwidget)
        self.choose_beamimage.setGeometry(QtCore.QRect(1050, 770, 171, 41))
        self.choose_beamimage.setObjectName(_fromUtf8("choose_beamimage"))
        self.choose_bindir = QtGui.QPushButton(self.centralwidget)
        self.choose_bindir.setGeometry(QtCore.QRect(1050, 740, 171, 41))
        self.choose_bindir.setObjectName(_fromUtf8("choose_bindir"))
        self.brightpix = QtGui.QSpinBox(self.centralwidget)
        self.brightpix.setGeometry(QtCore.QRect(880, 250, 57, 25))
        self.brightpix.setMaximum(2024)
        self.brightpix.setProperty(_fromUtf8("value"), 50)
        self.brightpix.setObjectName(_fromUtf8("brightpix"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(940, 250, 121, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.takesky = QtGui.QPushButton(self.centralwidget)
        self.takesky.setGeometry(QtCore.QRect(1050, 700, 171, 51))
        self.takesky.setObjectName(_fromUtf8("takesky"))
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(860, 390, 181, 511))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_36 = QtGui.QLabel(self.frame_7)
        self.label_36.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.cal_time = QtGui.QSpinBox(self.frame_7)
        self.cal_time.setGeometry(QtCore.QRect(20, 180, 57, 25))
        self.cal_time.setMaximum(10000)
        self.cal_time.setObjectName(_fromUtf8("cal_time"))
        self.cal_angle = QtGui.QDoubleSpinBox(self.frame_7)
        self.cal_angle.setGeometry(QtCore.QRect(90, 180, 62, 25))
        self.cal_angle.setMaximum(360.0)
        self.cal_angle.setObjectName(_fromUtf8("cal_angle"))
        self.goto_angle = QtGui.QDoubleSpinBox(self.frame_7)
        self.goto_angle.setGeometry(QtCore.QRect(90, 240, 62, 25))
        self.goto_angle.setObjectName(_fromUtf8("goto_angle"))
        self.label_37 = QtGui.QLabel(self.frame_7)
        self.label_37.setGeometry(QtCore.QRect(90, 220, 62, 17))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.frame_7)
        self.label_38.setGeometry(QtCore.QRect(20, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(90, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.do_cal_button = QtGui.QPushButton(self.frame_7)
        self.do_cal_button.setGeometry(QtCore.QRect(10, 120, 151, 41))
        self.do_cal_button.setObjectName(_fromUtf8("do_cal_button"))
        self.go_home_button = QtGui.QPushButton(self.frame_7)
        self.go_home_button.setGeometry(QtCore.QRect(10, 61, 151, 41))
        self.go_home_button.setObjectName(_fromUtf8("go_home_button"))
        self.goto_button = QtGui.QPushButton(self.frame_7)
        self.goto_button.setGeometry(QtCore.QRect(10, 220, 71, 51))
        self.goto_button.setObjectName(_fromUtf8("goto_button"))
        self.label_40 = QtGui.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(20, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.laser_toggle = QtGui.QCheckBox(self.frame_7)
        self.laser_toggle.setGeometry(QtCore.QRect(20, 270, 111, 41))
        self.laser_toggle.setObjectName(_fromUtf8("laser_toggle"))
        self.laser_label = QtGui.QLabel(self.frame_7)
        self.laser_label.setGeometry(QtCore.QRect(120, 270, 51, 41))
        self.laser_label.setObjectName(_fromUtf8("laser_label"))
        self.filter1 = QtGui.QRadioButton(self.frame_7)
        self.filter1.setGeometry(QtCore.QRect(20, 350, 102, 21))
        self.filter1.setAutoExclusive(False)
        self.filter1.setObjectName(_fromUtf8("filter1"))
        self.filter_buttonGroup = QtGui.QButtonGroup(arcons)
        self.filter_buttonGroup.setObjectName(_fromUtf8("filter_buttonGroup"))
        self.filter_buttonGroup.addButton(self.filter1)
        self.filter2 = QtGui.QRadioButton(self.frame_7)
        self.filter2.setGeometry(QtCore.QRect(20, 370, 102, 21))
        self.filter2.setAutoExclusive(False)
        self.filter2.setObjectName(_fromUtf8("filter2"))
        self.filter_buttonGroup.addButton(self.filter2)
        self.filter3 = QtGui.QRadioButton(self.frame_7)
        self.filter3.setGeometry(QtCore.QRect(20, 390, 102, 21))
        self.filter3.setAutoExclusive(False)
        self.filter3.setObjectName(_fromUtf8("filter3"))
        self.filter_buttonGroup.addButton(self.filter3)
        self.filter4 = QtGui.QRadioButton(self.frame_7)
        self.filter4.setGeometry(QtCore.QRect(20, 410, 102, 21))
        self.filter4.setAutoExclusive(False)
        self.filter4.setObjectName(_fromUtf8("filter4"))
        self.filter_buttonGroup.addButton(self.filter4)
        self.filter5 = QtGui.QRadioButton(self.frame_7)
        self.filter5.setGeometry(QtCore.QRect(20, 430, 102, 21))
        self.filter5.setAutoExclusive(False)
        self.filter5.setObjectName(_fromUtf8("filter5"))
        self.filter_buttonGroup.addButton(self.filter5)
        self.filter6 = QtGui.QRadioButton(self.frame_7)
        self.filter6.setGeometry(QtCore.QRect(20, 450, 102, 21))
        self.filter6.setChecked(True)
        self.filter6.setAutoExclusive(False)
        self.filter6.setObjectName(_fromUtf8("filter6"))
        self.filter_buttonGroup.addButton(self.filter6)
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(1060, 810, 101, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1060, 830, 46, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1060, 863, 46, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.RA_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.RA_lineEdit.setEnabled(False)
        self.RA_lineEdit.setGeometry(QtCore.QRect(1060, 840, 113, 20))
        self.RA_lineEdit.setObjectName(_fromUtf8("RA_lineEdit"))
        self.Dec_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.Dec_lineEdit.setEnabled(False)
        self.Dec_lineEdit.setGeometry(QtCore.QRect(1060, 880, 113, 20))
        self.Dec_lineEdit.setObjectName(_fromUtf8("Dec_lineEdit"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(900, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.vmin = QtGui.QSpinBox(self.centralwidget)
        self.vmin.setGeometry(QtCore.QRect(886, 350, 61, 25))
        self.vmin.setMaximum(1000000)
        self.vmin.setProperty(_fromUtf8("value"), 100)
        self.vmin.setObjectName(_fromUtf8("vmin"))
        self.vmax = QtGui.QSpinBox(self.centralwidget)
        self.vmax.setGeometry(QtCore.QRect(960, 350, 57, 25))
        self.vmax.setMaximum(1000000)
        self.vmax.setProperty(_fromUtf8("value"), 1500)
        self.vmax.setObjectName(_fromUtf8("vmax"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(940, 280, 62, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.contrast_mode = QtGui.QCheckBox(self.centralwidget)
        self.contrast_mode.setGeometry(QtCore.QRect(880, 300, 161, 31))
        self.contrast_mode.setObjectName(_fromUtf8("contrast_mode"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(890, 330, 62, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(960, 330, 62, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        arcons.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(arcons)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        arcons.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(arcons)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        arcons.setMenuBar(self.menubar)

        self.retranslateUi(arcons)
        QtCore.QObject.connect(self.close_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), arcons.close)
        QtCore.QMetaObject.connectSlotsByName(arcons)

    def retranslateUi(self, arcons):
        arcons.setWindowTitle(QtGui.QApplication.translate("arcons", "ARCONS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("arcons", "ARCONS Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("arcons", "Array Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("arcons", "Pulse Tube Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.open_shutter_radioButton.setText(QtGui.QApplication.translate("arcons", "Open Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.cycle_fridge_radioButton.setText(QtGui.QApplication.translate("arcons", "Cycle Fridge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("arcons", "Telescope Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("arcons", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("arcons", "Dec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("arcons", "UTC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("arcons", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("arcons", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("arcons", "Local Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("arcons", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("arcons", "LST", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("arcons", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.save_raw_checkBox.setText(QtGui.QApplication.translate("arcons", " Save Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("arcons", "Data Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("arcons", "Remaining time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("arcons", "SDR Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("arcons", "Exposure Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrate_data_checkBox.setText(QtGui.QApplication.translate("arcons", "Calibrate Data", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_observation_pushButton.setText(QtGui.QApplication.translate("arcons", "Stop Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.start_observation_pushButton.setText(QtGui.QApplication.translate("arcons", "Start Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("arcons", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.search_pushButton.setText(QtGui.QApplication.translate("arcons", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.frequency_tuneup_pushButton.setText(QtGui.QApplication.translate("arcons", "Frequency \n"
"Tune-up", None, QtGui.QApplication.UnicodeUTF8))
        self.target_lineEdit.setText(QtGui.QApplication.translate("arcons", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("arcons", "File name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("arcons", "Target name:", None, QtGui.QApplication.UnicodeUTF8))
        self.subtract_sky_radioButton.setText(QtGui.QApplication.translate("arcons", "Subtract Sky", None, QtGui.QApplication.UnicodeUTF8))
        self.image_color_radioButton.setText(QtGui.QApplication.translate("arcons", "Image Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("arcons", " Integration (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.options_radioButton.setText(QtGui.QApplication.translate("arcons", "Expand Controls-->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("arcons", "Additional Header Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.update_description.setText(QtGui.QApplication.translate("arcons", "Update in Header", None, QtGui.QApplication.UnicodeUTF8))
        self.continuous.setText(QtGui.QApplication.translate("arcons", "  Continuous Observing", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_number_label.setText(QtGui.QApplication.translate("arcons", "Displaying Plot for\n"
" Pixel Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("arcons", "Pixel Selection Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.drag_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Click && Drag", None, QtGui.QApplication.UnicodeUTF8))
        self.rect_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Single Click Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("arcons", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("arcons", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.circ_select_radioButton.setText(QtGui.QApplication.translate("arcons", "Single Click Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("arcons", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_beamimage.setText(QtGui.QApplication.translate("arcons", "Choose Beamimage", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_bindir.setText(QtGui.QApplication.translate("arcons", "Choose Bin Dir.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("arcons", "Saturated Pix", None, QtGui.QApplication.UnicodeUTF8))
        self.takesky.setText(QtGui.QApplication.translate("arcons", "Take Sky Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("arcons", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("arcons", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("arcons", "Cal Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("arcons", "Cal Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.do_cal_button.setText(QtGui.QApplication.translate("arcons", "Do Cal", None, QtGui.QApplication.UnicodeUTF8))
        self.go_home_button.setText(QtGui.QApplication.translate("arcons", "Go Home", None, QtGui.QApplication.UnicodeUTF8))
        self.goto_button.setText(QtGui.QApplication.translate("arcons", "GoTo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("arcons", "Filter Wheel", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_toggle.setText(QtGui.QApplication.translate("arcons", "Laser Box", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_label.setText(QtGui.QApplication.translate("arcons", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.filter1.setText(QtGui.QApplication.translate("arcons", "Filter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.filter2.setText(QtGui.QApplication.translate("arcons", "Filter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.filter3.setText(QtGui.QApplication.translate("arcons", "Filter 3", None, QtGui.QApplication.UnicodeUTF8))
        self.filter4.setText(QtGui.QApplication.translate("arcons", "Filter 4", None, QtGui.QApplication.UnicodeUTF8))
        self.filter5.setText(QtGui.QApplication.translate("arcons", "Filter 5", None, QtGui.QApplication.UnicodeUTF8))
        self.filter6.setText(QtGui.QApplication.translate("arcons", "Filter 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("arcons", "Testing Junk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("arcons", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("arcons", "Dec", None, QtGui.QApplication.UnicodeUTF8))
        self.RA_lineEdit.setText(QtGui.QApplication.translate("arcons", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Dec_lineEdit.setText(QtGui.QApplication.translate("arcons", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("arcons", "Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("arcons", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.contrast_mode.setText(QtGui.QApplication.translate("arcons", "Manually", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("arcons", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("arcons", "Max", None, QtGui.QApplication.UnicodeUTF8))

from mpl_pyqt4_widget import MPL_Widget
