#!/bin/bash
cp implementation/system.bit ../bit_files/chan_550_clean_2012_Jul_24_2017.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/chan_550_clean_2012_Jul_24_2017.bof
